# Generated by Django 5.2.8 on 2025-11-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ecommerce',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('manufracture_name', models.CharField(max_length=15)),
                ('prodution_date', models.DateField()),
                ('cost', models.IntegerField()),
                ('company', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
